### ISSUE TITLE
Puppet forge links are going to the old repo

### ISSUE THREAD

**Issue by khaefeli** [choria-plugins/puppetca-agent#4]
https://forge.puppet.com/choria/mcollective_agent_puppetca
=> Project url redirects to https://github.com/choria-legacy/mcollective-plugins

This confuses people maybe and they think the plugin isn't maintained anymore

**Comment by ripienaar** [comment]
thanks

**Comment by ripienaar** [comment]
fixed in latest release https://forge.puppet.com/choria/mcollective_agent_puppetca/readme

this module needs a whole rework to be puppet 6 compatible i bet
